name: Package (iOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  clean:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clean
      run: xcodebuild clean -scheme $SCHEME -destination "$DESTINATION"
      env:
          SCHEME: CrystalViewUtilities
          DESTINATION: platform=iOS Simulator,OS=16.0name=iPhone 13 Pro

  build:
    needs: clean

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clean Build
      run: xcodebuild build -scheme $SCHEME -destination "$DESTINATION"
      env:
          SCHEME: CrystalViewUtilities
          DESTINATION: platform=iOS Simulator,OS=16.0,name=iPhone 13 Pro
